version: "3.8"
services:

  keycloak-server:
    image: keycloak-server:latest
    container_name: keycloak-server
    ports:
      - "5091:5000"
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
    restart: unless-stopped
